version: '3'
services:
  app:
    build: .                
    image: rls-api:v1.0    
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb+srv://ikalumba221:Fb3LUGsfNAkK1ag2@rls.lm131.mongodb.net/RLS
    depends_on:
      - db

  db:
    image: mongo:4.4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: nestdb
